### ISSUE TITLE
Does not follow nextToken for listing task definitions in filterOutActiveImages

### ISSUE THREAD

**Issue by dominics** [trek10inc/ecr-cleaner#5]
In `filterOutActiveImages`, the `nextToken` on the `listTaskDefinitions` call is not followed. This means that if the user has more than 100 active task definitions ('active' as in AWS API, not meaning 'in use by ECR'), then all the task definitions after the first 100 will be skipped. (And if one of those definitions uses an image, it will not be filtered, and may be cleaned up!)

In general, I don't think the approach of `listTaskDefinitions -> describeTaskDefinitions` is going to work well, because the number of task definitions could be hundreds or thousands of times the number of container images in use by such task definitions (especially if the user isn't automatically marking outdated task definitions as inactive).

I guess it'll vary by AWS account and use case. But I think if you might have far less to page/iterate through if you instead looked at `listServices -> describeServices -> describeTaskDefinitions`, or even started by looking at running tasks rather than all task definitions.

**Comment by shortjared** [comment]
Hey! We just ran into this problem ourselves. Reviewing a fix now. 😦

**Comment by charlesguse** [comment]
Hey @dominics. We put up a changeset to fix this issue. We stuck with listTaskDefinitions but because pagination wasn't working properly, it started to hit the api limit. This was fixed by setting concurrency to 10.

Even though we ran into the issue already as @shortjared mentioned, thanks for reporting the issue.
