### ISSUE TITLE
Does not follow nextToken for listing images in getRepoImages

### ISSUE THREAD

**Issue by dominics** [trek10inc/ecr-cleaner#6]
Simple one, but it means that only 100 candidate images will be potentially cleaned at once. Not as bad as #5, because you can just re-run (as long as you always have less than 100 images you _don't_ want cleaned).

You're out of luck if you need more than 100 valid/not-cleaned tags.

**Comment by charlesguse** [comment]
Hey @dominics. We put up a changeset to fix this issue (that also fixed #5).

Thanks for reporting the issue.
