### ISSUE TITLE
Invalid parameter at 'imageIds' failed to satisfy constraint: 'Member must have length less than or equal to 100'

### ISSUE THREAD

**Issue by lodotek** [trek10inc/ecr-cleaner#8]
When I run `serverless function run main -s dev
` it outputs many lines of imageTags and imageDigests then eventually fails at the message below:

```
Serverless: Invalid parameter at 'imageIds' failed to satisfy constraint: 'Member must have length less than or equal to 100'  
Serverless: InvalidParameterException: Invalid parameter at 'imageIds' failed to satisfy constraint: 'Member must have length less than or equal to 100'
```

any ideas?

**Comment by wichon** [comment]
Some operations like batch_get_image and batch_delete_image, can receive up to 100 imageIds, so if you have more than 100 images, you have to process them in batches of 100 or less.

**Comment by charlesguse** [comment]
Hey there,

My most recent commit fixes this issue. Sorry for any inconvenience this caused!
